services:
  alfresco:
    image:  docker.crestsolution.com:8443/digiworks/alfresco:20250609125526
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dindex.subsystem.name=elasticsearch
        -Delasticsearch.createIndexIfNotExists=true
        -Delasticsearch.host=elasticsearch
        -Delasticsearch.port=9200
        -Dshare.host=localhost
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080         
        -Daudit.enabled=true
        -Daudit.alfresco-access.enabled=true
        -Daudit.alfresco-access.sub-actions.enabled=false
        -Daudit.filter.alfresco-access.transaction.action="READ;.*"
        -Daudit.filter.alfresco-access.transaction.type="~rc:oauth2Credentials;~digi:digiconfig;~cm:person;cm:folder;cm:content;st:site;.*"
        -Daudit.filter.alfresco-access.default.enabled=true
        -Daudit.filter.alfresco-access.default.user="~null;.*"
        -Daudit.filter.alfresco-access.default.path="~/app:company_home/st:sites/cm:surf-config;~/sys:system;~/cm:categoryRoot;~/cm:multilingualRoot;/app:company_home/st:sites/.*"
        -Daudit.filter.alfresco-access.transaction.user="~System;~null;.*"
        -Daudit.filter.alfresco-access.transaction.path="~/app:company_home/app:dictionary/.*;~/sys:system/sys:authorities/.*;~/app:company_home/st:sites/cm:surf-config/.*;/app:company_home/st:sites/.*"
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Ddsync.service.uris=http://localhost:9090/alfresco
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-
      interval: 120s
      timeout: 60s
      retries: 3
      start_period: 1m
    ports:
      - "9191:8080"
    volumes:
      - alf_data:/usr/local/tomcat/alf_data
      - ./resources/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
      - ./resources/alfresco.lic:/usr/local/tomcat/shared/classes/alfresco/extension/license/alfresco.lic
      - ./resources/TextLicense.l4j:/usr/local/tomcat/shared/classes/alfresco/module/com.tsgrp.opencontent/license/TextLicense.l4j
      - ./resources/acs.sh:/usr/local/bin/acs.sh
      - ./resources/legal-contract.docx:/usr/local/bin/legal-contract.docx
      - ./resources/corporate-contract.docx:/usr/local/bin/corporate-contract.docx
      - ./resources/documentReminder.html.ftl:/usr/local/bin/documentReminder.html.ftl
      - ./resources/folderReminder.html:/usr/local/bin/folderReminder.html
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/acs.sh & exec /usr/local/tomcat/bin/catalina.sh run"]

  transform-router:
    image:  quay.io/alfresco/alfresco-transform-router:4.1.7
    platform: linux/amd64
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      ACTIVEMQ_URL: nio://activemq:61616
      CORE_AIO_URL: http://transform-core-aio:8090
      FILE_STORE_URL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    ports:
      - "8095:8095"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/actuator/health"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 20s
    depends_on:
      activemq:
        condition: service_healthy
      shared-file-store:
        condition: service_healthy
  transform-core-aio:
    image:  quay.io/alfresco/alfresco-transform-core-aio:5.1.7
    platform: linux/amd64
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      ACTIVEMQ_URL: nio://activemq:61616
      FILE_STORE_URL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/ready"]
      interval: 200s
      timeout: 20s
      retries: 3
      start_period: 100s
    depends_on:
      activemq:
        condition: service_healthy
      shared-file-store:
        condition: service_healthy
  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:4.1.7
    platform: linux/amd64
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - "8099:8099"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/ready"]
      interval: 200s
      timeout: 20s
      retries: 30
      start_period: 100s
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs
  share:
    image: docker.crestsolution.com:8443/digiworks/share:20250522151856
    platform: linux/amd64
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
    ports:
       - "9292:8080"
  ooi-service:
    image: quay.io/alfresco/alfresco-ooi-service:2.0.0
    platform: linux/amd64
    environment:
       JAVA_OPTS: >-
           -Dalfresco.base-url=http://alfresco:8080
    ports:
       - "9095:9095"
  postgres:
    image: postgres:16.5
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
 #   ports:
 #     - "5432:5432"
    volumes:
      - acs-database-data:/var/lib/postgresql/data/
    

  elasticsearch:
    image:  arm64v8/elasticsearch:8.17.6
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl -s -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"]
      interval: 180s
      timeout: 120s
      retries: 3
      start_period: 2m  
    volumes:
      - esdata:/usr/share/elasticsearch/data

  search:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing:5.0.0
    platform: linux/amd64
    environment:
      ALFRESCO_ACCEPTED_CONTENT_MEDIA_TYPES_CACHE_BASE_URL: >-
        http://transform-core-aio:8090/transform/config
      ALFRESCO_SHAREDFILESTORE_BASEURL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
      transform-core-aio:
        condition: service_healthy
      shared-file-store:
        condition: service_healthy
  search-reindexing:
    image: quay.io/alfresco/alfresco-elasticsearch-reindexing:5.0.0
    restart: on-failure:10
    platform: linux/amd64
    environment:
      ALFRESCO_ACCEPTED_CONTENT_MEDIA_TYPES_CACHE_BASE_URL: >-
        http://transform-core-aio:8090/transform/config
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      SPRING_DATASOURCE_USERNAME: alfresco
      SPRING_DATASOURCE_PASSWORD: alfresco
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    volumes:
      - ./resources/reindex.prefixes-file.json:/opt/BOOT-INF/classes/reindex.prefixes-file.json
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_started
      alfresco:
        condition: service_healthy
  activemq:
    image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP
    healthcheck:
      test: ["CMD", "/opt/activemq/bin/activemq", "query", "--objname", "type=Broker,brokerName=*,service=Health", "|", "grep", "Good"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  digiworks-enterprise:
    image: docker.crestsolution.com:8443/digiworks/adf:20250609171334
    platform: linux/amd64
    environment:
      APP_CONFIG_ECM_HOST: "http://192.168.50.146:8080"
      APP_CONFIG_BPM_HOST: "http://192.168.50.146:8080"
      APP_CONFIG_PROVIDER: "ALL"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      APP_CONFIG_OAUTH2_CLIENTID: "alfresco-client"
      APP_CONFIG_OAUTH2_SCOPE: "\"openid\""
      APP_CONFIG_OAUTH2_SECRET: "\"\""
      APP_CONFIG_OAUTH2_IMPLICIT_FLOW: "true"
      APP_CONFIG_OAUTH2_REDIRECT_LOGIN: "/"
      APP_CONFIG_OAUTH2_REDIRECT_LOGOUT: "/"
      APP_CONFIG_OAUTH2_REQUIRE_HTTPS: "false"
      APP_CONFIG_OAUTH2_SILENT_LOGIN: "true"
      APP_CONFIG_OAUTH2_HOST: ""
      APP_CONFIG_AOS_HOST: "http://192.168.50.146:8080/alfresco/aos"
      APP_CONFIG_BASE_DOCUMENT_SHARE_URL: "http://192.168.50.146:8080/digiworks-enterprise/#/preview/s/"
      APP_CONFIG_BASE_FOLDER_SHARE_URL: "http://192.168.50.146:8080/digiworks-enterprise/#/guest-access/"
      APP_CONFIG_AEV_ENDPOINTS: "http://192.168.50.146:8080/OpenAnnotate"
      APP_CONFIG_AEV_ENDPOINTS_VIDEO: "http://192.168.50.146:8080/OpenAnnotateVideo" 
      NGINX_DIR: "/usr/share/nginx/html/digiworks-enterprise"
    depends_on:
      - alfresco
      - process
    volumes:
      - ./resources/digiworks-nginx.conf:/etc/nginx/nginx.conf

  document-compare:
    image: docker.crestsolution.com:8443/digiworks/document-compare:v5
    depends_on:
      - alfresco
      - transform-router
    platform: linux/amd64
    environment:
      CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME: "admin"
      CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD: "admin"
      CONTENT_SERVICE_URL: "http://alfresco:8080"
      TRANSFORM_OFFICE_URL: "http://transform-core-aio:8090/transform"


  maria-db:
    image: mariadb:11.7.1-rc
    platform: linux/amd64
    container_name: mariadb-db
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "alfrescoai"
      MARIADB_DATABASE: "alfrescoai"
    volumes:
      - ./ai-data/mariadb_data:/var/lib/mysql

  ai-scheduler-elastic:
    image: docker.crestsolution.com:8443/digiworks-ai/ai-scheduler-elastic:v2.1.0
    platform: linux/amd64
    depends_on:
      elasticsearch:
        condition: service_healthy
      alfresco:
        condition: service_healthy
    volumes:
      - shared-ai-data:/mnt/ai
    environment:
      JAVA_OPTS: >-
          -Dcontent.service.url=http://alfresco:8080
          -Dcontent.service.security.basicAuth.username=admin
          -Dcontent.service.security.basicAuth.password=admin
          -Delasticsearch.host=elasticsearch 
          -Dspring.elasticsearch.uris=http://elasticsearch:9200
          -Dspring.ai.openai.embedding.api-key=AIzaSyByR5...
  
  ai-chat-elastic:
    image: docker.crestsolution.com:8443/digiworks-ai/ai-chat-elastic:v2.1.0
    platform: linux/amd64
    depends_on:
      elasticsearch:
        condition: service_healthy
      alfresco:
        condition: service_healthy
    volumes:
      - shared-ai-data:/mnt/ai
    environment:
      JAVA_OPTS: >-
          -Dcontent.service.url=http://alfresco:8080
          -Dcontent.service.security.basicAuth.username=admin
          -Dcontent.service.security.basicAuth.password=admin
          -Delasticsearch.host=elasticsearch 
          -Dspring.elasticsearch.uris=http://elasticsearch:9200 
          -Dspring.datasource.url=jdbc:mariadb://maria-db:3306/alfrescoai
          -Dspring.datasource.username=root
          -Dspring.datasource.password=root
          -Dspring.ai.openai.embedding.api-key=AIzaSyByR5...
          -Dspring.ai.openai.chat.api-key=AIzaSyByR5...
          -Dspring.ai.openai.api-key=AIzaSyByR5...
          -Dspring.ai.openai.chat.options.model=gemini-2.0-flash-001
          -Dspring.ai.openai.model=gemini-2.0-flash-001

  ai-alfresco-rules-service:
    image: docker.crestsolution.com:8443/digiworks-ai/alfresco-ai-services-rules:v1.4.0
    platform: linux/amd64
    depends_on:
      activemq:
        condition: service_healthy
      alfresco:
        condition: service_healthy 
    environment:
        JAVA_OPTS: >-
          -Dcontent.service.url=http://alfresco:8080
          -Dcontent.service.security.basicAuth.username=admin
          -Dcontent.service.security.basicAuth.password=admin
          -Dspring.activemq.brokerUrl=tcp://activemq:61616
          -Dai.serviceUrl=http://ai-chat-elastic:8002
          -Dtransform.office.url=http://transform-core-aio:8090/transform

  process:
    image:  docker.crestsolution.com:8443/digiworks/aps-activiti:latest
    platform: linux/amd64
    environment:
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
    volumes:
      - aps_data:/usr/local/data
      - ./resources/activiti-app.properties:/usr/local/tomcat/lib/activiti-app.properties
      - ./resources/aps.sh:/usr/local/bin/aps.sh
      - ./resources/Dynamic-Collaboration-Workflow.zip:/usr/local/bin/Dynamic-Collaboration-Workflow.zip
      - ./resources/ContractManagement.zip:/usr/local/bin/ContractManagement.zip
      - ./resources/activiti.lic:/usr/local/tomcat/lib/activiti.lic
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/aps.sh & exec /usr/local/tomcat/bin/catalina.sh run"]
    ports:
      - 9080:8080
    depends_on:
      - postgres
      - alfresco
      - share
      - postgresaps
      - processadmin 

  processadmin:
    image: docker.crestsolution.com:8443/digiworks/aps-admin:latest
    ports:
      - 8081:8080
    depends_on:
      - postgresadmin
    volumes:
     - ./resources/activiti-admin.properties:/usr/local/tomcat/lib/activiti-admin.properties

  postgresaps:
    image: postgres:16.5
    ports:
      - 5433:5433
    platform: linux/amd64
    environment:
      POSTGRES_DB: activiti
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: -p 5433
    volumes:
      - aps-database-data:/var/lib/postgresql/data/

  postgresadmin:
    image: postgres:16.5
    ports:
      - 5434:5434
    platform: linux/amd64
    environment:
      POSTGRES_DB: activiti-admin
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: -p 5434
    volumes:
      - aps-admin-database-data:/var/lib/postgresql/data/
  proxy:
    image: nginx
    ports:
      - "8080:8080"
    depends_on:
      - digiworks-enterprise
      - alfresco
      - share
      - process
      - postgresadmin
      - ai-chat-elastic
      - document-compare
      - ooi-service
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf
     # - ./resources/server.key:/etc/nginx/certs/server.key
     # - ./resources/server.crt:/etc/nginx/certs/server.crt
volumes:
  aps_data:
  esdata:
  alf_data:
  acs-database-data: 
  aps-admin-database-data:
  aps-database-data:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
  shared-ai-data:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./ai-data
